version: "2.1"

volumes:
  kong_data: {}

networks:
  kong-net:

services:
  kong:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    container_name: kong-tutorial-dbless-kong
    user: "${KONG_USER:-kong}"
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
    networks:
      - kong-net
    ports:
      - "8000:8000/tcp"
      - "8001:8001/tcp"
      - "8443:8443/tcp"
      - "8444:8444/tcp"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure
    volumes:
      - ./kong.conf:/etc/kong/kong.conf:ro

  my-service-1:
    image: nginx:latest
    container_name: kong-tutorial-dbless-service-1
    networks:
      - kong-net
